"""

The SlobsConnection constructor needs to be given details about how to connect to the
StreamLabs OBS application.

It needs to know which host is running the application, which port it is listening to,
and the "API Token".

The API Token is like a password. It is generated by the application and
shared with any tools that want to talk to it. It should not be shared with others; if
it is, a new token should be generated.

----

To obtain all these details, start StreamLabs OBS, open the settings page, and select
"Remote Control". A (blurry) QR code will be displayed. Do not show that QR code on
your stream.

If you click on the QR code, and click "Show Details" underneath it you will be given
the following details:

    * API token

    * Port: This should default to 59650. If it is a different value, your Python
    application will need to know this.

    * IP addresses: If your application is on a different host to StreamLabs OBS, your
    Python application will need to know one of the IP addresses offered.

**Note:** For simplicity, the examples and exercises assume that the default port is
being used and it is running on the same machine.

----

When running the examples or exercises, you will be prompted to type in the API token
each time.

Alternatively, you can paste it into a file called `token.txt` in the current directory
or the directory this file is in.
(Contributors: Do not commit this file!)

"""

from pathlib import Path

def token():
    try:
        with open("token.txt", "r") as token_file:
            return token_file.read()
    except FileNotFoundError:
        try:
            with open(Path(__file__).parent /"token.txt", "r") as token_file:
                return token_file.read()
        except FileNotFoundError:
            return input("API Token: ")
